const PanoImg = [
  {
    imageLink:
      "https://noirlab.edu/public/media/archives/images/publicationjpg/20220408PachonFPano35mmRubinAuxi_MW_EQ-001-CC-002.jpg",
  },
  {
    imageLink:
      "https://noirlab.edu/public/media/archives/images/screen/2022_03_30_Gemini_North_360_Outside_10-CC.jpg",
  },
  {
    imageLink:
      "https://noirlab.edu/public/media/archives/images/large/7950_tio_TMT_VR_0037-CC.jpg",
  },
  {
    imageLink:
      "https://noirlab.edu/public/media/archives/images/publicationjpg/360Pano_Sara_Burell_Vis_Center_Roll_Off_View-CC.jpg",
  },
  {
    imageLink:
      "https://noirlab.edu/public/media/archives/images/publicationjpg/360Pano_Kitt_Peak_Visitor_Center_Outside2-CC.jpg",
  },
  {
    imageLink:
      "https://noirlab.edu/public/media/archives/images/publicationjpg/Mayall_360_1-CC_78.jpg",
  },
  {
    imageLink:
      "https://noirlab.edu/public/media/archives/images/publicationjpg/VLBA_360_4-CC.jpg",
  },
  {
    imageLink:
      "https://noirlab.edu/public/media/archives/images/publicationjpg/Pachon-Drone-pano-360-1-CC-ex.jpg",
  },
  {
    imageLink:
      "https://noirlab.edu/public/media/archives/images/publicationjpg/GS-360-pic-2-CC3.jpg",
  },
  {
    imageLink:
      "https://noirlab.edu/public/media/archives/images/publicationjpg/2022_04_07_Pano360_Rubin_Parking-CC.jpg",
  },
  {
    imageLink:
      "https://noirlab.edu/public/media/archives/images/publicationjpg/2022_03_25_360Pano_UArizona_0p9_from_Hill_2-CC.jpg",
  },
  {
    imageLink:
      "https://noirlab.edu/public/media/archives/images/publicationjpg/2022_04_09_Pano360_SOAR1-CC.jpg",
  },
  {
    imageLink:
      "https://noirlab.edu/public/media/archives/images/publicationjpg/Group_3-DJI_0001_CC_DJI_0026_CC-26-CC2ex.jpg",
  },
];

export default PanoImg;
